<h1 class="text-center mb-5">Lettre de Talleyrand à Napoléon lui exposant son projet de paix générale</h1>
<div class="container-fluid p-2 bg-warning"></div>
<div class="container justify-content-center mt-5">
    <p class="mb-3 mt-3">Dans l’éloignement où je suis de Votre Majesté, ma plus douce ou plutôt mon unique consolation est de me rapprocher d’elle, autant qu’il est en moi, par le souvenir et par la prévoyance. Le passé m’explique le présent et ce qu’a fait Votre Majesté me devient un présage de ce qu’elle doit faire ; car, tandis que les déterminations des hommes ordinaires varient sans cesse, celles de Votre Majesté, prenant sa source dans sa magnanimité naturelle, sont, dans les mêmes circonstances, irrévocablement les mêmes.</p>
    <div class="p-1 bg-warning col-12"></div>
    <p class="mb-3 mt-3">Lorsque Votre Majesté quitta Strasbourg, une seule chose tempérait me regrets. C’était la certitude qu’elle marchait à la victoire. A peine quelques jours se sont écoulés, à peine Votre Majesté a-t-elle rencontré l’ennemi, et déjà elle a vaincu. Mais quand le vulgaire ne voit dans les succès de Votre Majesté que ces succès même, ceux qui songent qu’après les mémorables campagnes de l’an IV et de l’an V, au 18 brumaire, après la journée de Marengo, et en d’autres circonstances non moins solennelles, Votre Majesté n’a profité de ses triomphes que pour offrir la paix à ses ennemis, ceux qui savent qu’elle ne considère chaque victoire que comme un gage de la paix après laquelle elle soupire, ne doutent point, qu’après avoir remporté dans cette guerre des avantages signalés sur l’Autriche, elle ne cède encore au noble penchant de sa grande âme.</p>
    <div class="p-1 bg-warning col-12"></div>
    <p class="mb-3 mt-3">Il ne m’appartient pas de rechercher quel était le meilleur système de guerre : Votre Majesté le révèle en ce moment à ses ennemis et à l’Europe étonnée. Mais voulant lui offrir un tribut de mon zèle, j’ai médité sur la paix future, objet qui, étant dans l’ordre de mes fonctions, a de plus un attrait particulier pour moi, parce qu’il se lie plus étroitement au bonheur de Votre Majesté.</p>
    <div class="p-1 bg-warning col-12"></div>
    <p class="mb-3 mt-3">L’Europe compte aujourd’hui quatre grandes puissances ; car dans ce rang je ne mets point la Prusse ; elle est grande dans l’opinion, parce qu’un de ses monarques fit de grandes choses, et parce qu’on s’est habitué à confondre avec Frédéric II l’Etat dont il fit la gloire ; mais, avec un territoire morcelé, ouvert de toutes parts, un sol généralement ingrat, une population de dix millions de sujets seulement, peu d’industrie et de capitaux, elle n’est réellement que la première des puissances de second ordre.</p>
    <div class="p-1 bg-warning col-12"></div>
    <p class="mb-3 mt-3">A la tête des grandes puissances est la France, plus forte que chacune des trois autres, capable même de leur résister à toutes, seule puissance parfaite parce que seule elle réunit dans une juste proportion, les deux éléments de grandeur qui sont inégalement répartis entre les autres, à savoir, les hommes et la richesse.</p>
    <div class="p-1 bg-warning col-12"></div>
    <p class="mb-3 mt-3">Des trois puissances qui partagent avec elle la haute influence en Europe, deux sont ses rivales et ses ennemis naturelles. La troisième, séparée d’elle par d’immenses espaces, n’est point directement son ennemie, mais elle l’est indirectement, comme ennemie naturelle de ses plus anciens alliés.</p>

</div>